apiVersion: v1
kind: Service
metadata:
  name: selenium-srv
  labels:
    app: selenium-srv
spec:
  selector:
    app: selenium-hub
  ports:
  - name: selenium-hub-tcp
    port: 4444
    nodePort: 30001
    targetPort: 4444
  type: NodePort